name: restaurants-api
on: 
  push:
    branches: [deployment]
  pull_request:
    branches: 
    - deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4.2.2
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v4.2.0
          with:
            dotnet-version: 8.0.x
        - name: Restore dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore
        - name: Test
          env:
            ASPNETCORE_ENVIRONMENT: Development
          run: dotnet test --no-build --logger "trx;LogFileName=test_results.trx"
